// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BasciMenuItem: typeof import('./src/components/Menu/src/components/BasciMenuItem.vue')['default']
    BasicMenu: typeof import('./src/components/Menu/src/BasicMenu.vue')['default']
    BasicSubMenuItem: typeof import('./src/components/Menu/src/components/BasicSubMenuItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    MenuItemContent: typeof import('./src/components/Menu/src/components/MenuItemContent.vue')['default']
    PageWrapper: typeof import('./src/components/Page/src/PageWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
